### ISSUE TITLE
datasets and debug

### ISSUE THREAD

**Issue by SunshineMiles** [YerevaNN/warp#11]
Thank you very much for your work. I would like to ask you some questions about the code. First of all, how can I change the datasets into my own? Second, I want to debug from.sh, but I can't find the program entry

**Comment by mahnerak** [comment]
Hi @SunshineMiles ,

I apologize for the delayed response. It seems that this issue slipped through my notifications, and I only saw it now that you've closed the request.

---

Regarding your first question, our implementation accepts dataset configurations that are compatible with Hugging Face's datasets library. You can simply modify the dataset configuration file to point to your own dataset, and the code should work seamlessly.
Reference: https://github.com/YerevaNN/WARP/blob/32b455faa7cb9c2f7cd40d45fe24a74c74be0ba9/configs/warp.jsonnet#L56-L59
So if you want, for example, the `banking_77` from https://huggingface.co/datasets/ought/raft , then you set `path` to `ought/raft` and `name` to `banking_77`. These hyperparameters are demonstrated to be fed using environment params like `export HPARAMS = { ...` in README.

---

As for debugging, it appears that you are looking for guidance on how to debug a non-script Python program (if I understood you correctly). You can do this by modifying the `launch.json` (in case of VS Code) file with the following content:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Module",
            "type": "python",
            "request": "launch",
            "module": "allennlp",
            "args": ["train", ...ALL THE REST ARGS HERE... ],
            "justMyCode": true,
            "env": {
                "HPARAMS": HPARAMS HERE
            }
        }
    ]
}
```

**Comment by SunshineMiles** [comment]
Thank you for your reply. The reason for closing is that I solved these two problems and I used pycharm for parameter passing. Again, thank you very much for your work. However, I still have two problems: the first is that in the code published on GitHub, only predict.py is used for the model, not evaluate.py.I want to know, if I need to test, what command script to run
![image](https://user-images.githubusercontent.com/110074827/233303216-7b66a139-4b4a-478d-9574-300833e3cbd7.png)

The second question is that the length of tokens input in transformer model is 512. However, I find through the data set that 512 is not reached. Will data be automatically filled? Also, if I have more than 512 tokens, how many tokens should I choose? prompts usually range from 1 to 20, and how many tokens should I keep when I input them.

**Comment by mahnerak** [comment]
1. I use predict.py to create outputs in respectable GLUE / SuperGLUE formats, to make sure the evaluation is done using scripts provided by the benchmarks, so we'll know 100% it's correct / comparable. Just use original evaluation script from benchmarks to run on the outputs.

2. I want to highlight that 512 may be **the maximum** length. Transformers are can receive variable number of tokens less than that. We pad only all the sentences in the same batch.
For performance reasons, we make sure to pad to a multiple of 8 lengths, as the latests NVidia GPUs are optimized to run TensorCores on 8x lengths.
https://github.com/YerevaNN/WARP/blob/32b455faa7cb9c2f7cd40d45fe24a74c74be0ba9/configs/warp.jsonnet#L68-L76

**Comment by SunshineMiles** [comment]
Thank you for your answer, but I still have a few questions.
1. First question, first warp only fills sentences in the same batch, if there are 8 sentences in the batch, does it fill 8 times as many? Am I reading this correctly.
2. The second question is whether each batch of data builds its own vocabulary during the construction of the vocabulary, or whether there is already a fixed vocabulary.Which method of constructing thesaurus is used?
3. What method is used in the process of tokenizer?
Looking forward to your reply. Thank you very much
