### ISSUE TITLE
No module named 'aim.sdk.session

### ISSUE THREAD

**Issue by jianzhengming** [YerevaNN/warp#9]
Hi, thanks for your nice work.
However, when I ran the follow code you provide:
for DATASET in 'cola' 'sst2' 'mrpc' 'qqp' 'stsb' 'mnli' 'rte' 'wnli' 'qnli'
do
    export HPARAMS='{
        "dataset": "'$DATASET'",
        "lr": 0.0001,
        "num_epochs": 20,
        "prompts": [],
        "reorder_optimized": false,
        "max_batch_size": 8,
        "max_tokens_sq": 262144, "on_logits":  false, "pooling_index":  null, "seed":  1}'
    python3 -m allennlp train \
    -s .aim/baseline-linear-${DATASET} configs/warp.jsonnet
done
,
I encountered the follow problem: 
ModuleNotFoundError: No module named 'aim.sdk.session'.
And I check the version of package "aim = 3.0.2" and the functions in aim.sdk. I did not find the function "session".
Do I get the wrong aim version?

**Comment by mahnerak** [comment]
Yes, it does not work with aim v3 yet. Please make sure installing aim v2.

**Comment by jianzhengming** [comment]
Hi, I'm still confused. I process the "pip install aim==2", yet it cannot install the aim v2.

**Comment by jianzhengming** [comment]
Hi, I'm still confused. I process the "pip install aim==2", yet it encounters the PackageNotFoundError. I track the documentation about the aim package (https://aimstack.readthedocs.io/en/latest/overview.html), and I cannot find the any information about the function "aim.sdk.session".

**Comment by jianzhengming** [comment]
Hi, I fix this problem by pip install aim=2.3. 

And I closed this issue. Thanks for your answers.
